feeds:
  - name: BBC World
    url: https://feeds.bbci.co.uk/news/world/rss.xml
  - name: The Guardian – World
    url: https://www.theguardian.com/world/rss
  - name: Le Monde – International
    url: https://www.lemonde.fr/international/rss_full.xml
  - name: DW – All (EN)
    url: https://rss.dw.com/rdf/rss-en-all
  - name: France 24 – International (EN)
    url: https://www.france24.com/en/rss
  - name: France 24 – International (FR)
    url: https://www.france24.com/fr/rss
  - name: Al Jazeera – All
    url: https://www.aljazeera.com/xml/rss/all.xml
