- name: Commit feed.json (pull-safe)
  shell: bash
  run: |
    set -e
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add feed.json
    DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    git commit -m "update feed ${DATE}" || echo "no changes"
    git pull --rebase origin main || true
    for i in 1 2 3; do
      if git push; then break; fi
      sleep 2
      git pull --rebase origin main || true
    done
