name: build-and-publish-feed
on:
  schedule:
    - cron: "*/30 * * * *"   # relance automatiquement toutes les 30 minutes
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # pour enregistrer feed.json dans le dépôt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python aggregateur.py
      - name: Commit feed.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "update feed" || echo "no changes"
          git push
